data:
  include_mesh_pos: True
  normalization_method: "standard" # 'standard' or 'centroid'
  max_trajs: 1500
  tfrecord_path: "raw_data/train.tfrecord"
  meta_path: "raw_data/meta.json"
  output_dir: "data"
